#!/usr/bin/env bash

APP="requesters" # name of your release

BUILD_HOST="162.243.84.159" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/tmp/requesters/builds" # build directory on build host

PRODUCTION_HOSTS="162.243.84.159"
# PRODUCTION_HOSTS="162.243.84.159 146.185.146.193 159.203.60.44"
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/root/requesters" # deploy directory on production hosts

LINK_VM_ARGS=/root/requesters/requesters/vm.args
