defmodule Models.Timeline do
  defstruct identifier: nil,
    feed_type: nil,
    name: nil,
    artist: nil,
    itunes_link: nil,
    description: nil,
    author: nil,
    user_identifier: nil,
    artist_identifier: nil,
    published_at: nil,
    likes_count: 0,
    picture: nil,
    source_link: nil,
    youtube_id: nil,
    youtube_link: nil,
    message: nil,
    album: nil,
    stream: nil,
    link: nil,
    import_source: nil,
    author_picture: nil,
    category: nil,
    to: [],
    view_count: 0,
    duration: 0
end
